### ISSUE TITLE
Replace parentStatement attribute in class Statement

### ISSUE THREAD

**Issue by le-minhphuc** [CS3201-T10/SPA#31]
In class Statement:
- Replace parentStatement with parentStatementContainer (of type StatementContainer)
- Replace getParentStatement with getParentContainer (return value of type StatementContainer)
@ShermineJong What do you think about these changes? I haven't made the changes yet btw

**Comment by ShermineJong** [comment]
I think not implementing the parent container would be a better solution because it may be quite complicated when implementing things across the procedure and statement for example getting the statement number and getting the procedure name. I think it would be better if we seperate them.

**Comment by ShermineJong** [comment]
Is it ok if I just add in the API in the procedure for the API that i use?

**Comment by le-minhphuc** [comment]
Hmm in my opinion it is better to have StatementContainer class because the code for Procedure, WhileStatement, and later IfStatement are very similar; so it will be better to abstract all the similarities into a StatementContainer class.

Regarding the complication with getting statement number of a parent container, I think it can be solved with static_casting the object to WhileStatement (if it is indeed a WhileStatement) and get statement number. Likewise, getting procedure name of a parent container can be done by static_cast the object to Procedure and use getName() method of Procedure class.

**Comment by ShermineJong** [comment]
I had Implemented accordingly
