### ISSUE TITLE
gitignore .log and .tlog files

### ISSUE THREAD

**Issue by le-minhphuc** [CS3201-T10/SPA#37]
I receive notice from @Crsytral that there are lots of .log and .tlog files being pushed to our repo.
@LookRain Are they supposed to be ignored based on the .gitignore file that you created? If not, can I seek your help in adding these types of files to .gitignore as I'm not very familiar with this

**Comment by le-minhphuc** [comment]
@Crsytral I just checked the .log and .tlog files. Not too many of them right? E.g. I only see a few under SPA/Debug folder

**Comment by LookRain** [comment]
file types that can be ignored safely seem to be poorly documented poorly on the internet... logs and tlogs files might need to be kept. I'll change the gitignore accordingly.
