### ISSUE TITLE
Remove varUses and varModifies from StatementContainer

### ISSUE THREAD

**Issue by le-minhphuc** [CS3201-T10/SPA#38]
Suggestion from @ShermineJong , which I agree with:
Move varUses and varModifies from StatementContainer to Procedure to avoid ambiguity.
Issue is that WhileStatement inherit from both StatementContainer and Statement, with both having varUses and varModifies.
Some related issues:
- Remove updateVarUses() and updateVarModifies() methods in StatementContainer class.
- Implement those in Procedure class.
- Implement those in Statement class.

**Comment by ShermineJong** [comment]
Done
